autocom/controllers/AccountingController.php
<?php

namespace app\controllers;

use Yii;
use app\controllers\SecureController;
use app\models\Modal;
use app\models\Kas;
use app\models\Tanah;
use app\models\Bangunan;
use app\models\Hutang;
use app\models\Piutang;
use app\models\TransaksiHp;

class AccountingController extends SecureController{

	public $layout = "accounting_layout";

	public function actionIndex(){
		return $this->render('index');
	}

	/**
	*
	* MODAL
	*/

	public function actionModalManagement(){
		if($this->isSelectAllowed()){
			return $this->render('list_modal');	
		}else{
			echo "You don't have access here";die;
		}
	}

	public function actionAddModal(){
		if($this->isInsertAllowed()){
			if(Yii::$app->request->post()){

				list($bulan, $tanggal, $tahun) = explode("/", Yii::$app->request->post()['tanggal']);

				$modal = new Modal();
				$modal->jumlah = Yii::$app->request->post()['jumlah'];
				$modal->keterangan = Yii::$app->request->post()['keterangan'];
				$modal->tanggal = "$tahun-$bulan-$tanggal";
				$modal->save();
				/*return $this->render('role_list');*/
				return $this->redirect(['accounting/modal-management']);
			}

        	return $this->render('add_modal');
        }else{
        	echo "You don't have access here";die;	
        }
	}

	public function actionUpdateModal(){
		if($this->isUpdateAllowed()){
			if(Yii::$app->request->post()){
				
				list($bulan, $tanggal, $tahun) = explode("/", Yii::$app->request->post()['tanggal']);

				$modal = Modal::findOne(Yii::$app->request->get()['id']);
				$modal->jumlah = Yii::$app->request->post()['jumlah'];
				$modal->keterangan = Yii::$app->request->post()['keterangan'];
				$modal->tanggal = "$tahun-$bulan-$tanggal";
				$modal->update();
				/*return $this->render('role_list');*/
				return $this->redirect(['accounting/modal-management']);
			}

        	return $this->render('update_modal');
        }else{
        	echo "You don't have access here";die;	
        }
	}

	public function actionDeleteModal(){
		if($this->isDeleteAllowed()){
			if(Yii::$app->request->get()){
				Modal::deleteAll('id_modal = '.Yii::$app->request->get()['id']);

				/*return $this->render('role_list');*/
				return $this->redirect(['accounting/modal-management']);
			}

        	return $this->render('list_modal');
        }else{
        	echo "You don't have access here";die;	
        }
	}

	/**
	*
	* KAS
	*/

	public function actionKasManagement(){
		if($this->isSelectAllowed()){
			return $this->render('list_kas');	
		}else{
			echo "You don't have access here";die;
		}
	}

	public function actionAddKas(){
		if($this->isInsertAllowed()){
			if(Yii::$app->request->post()){

				list($bulan, $tanggal, $tahun) = explode("/", Yii::$app->request->post()['tanggal']);

				$kas = new Kas();
				$kas->tipe = Yii::$app->request->post()['tipe'];
				$kas->jumlah = Yii::$app->request->post()['jumlah'];
				$kas->deskripsi = Yii::$app->request->post()['deskripsi'];
				$kas->tanggal = "$tahun-$bulan-$tanggal";
				$kas->save();
				/*return $this->render('role_list');*/
				return $this->redirect(['accounting/kas-management']);
			}

        	return $this->render('add_kas');
        }else{
        	echo "You don't have access here";die;	
        }
	}

	public function actionUpdateKas(){
		if($this->isUpdateAllowed()){
			if(Yii::$app->request->post()){
				
				list($bulan, $tanggal, $tahun) = explode("/", Yii::$app->request->post()['tanggal']);

				$modal = Kas::findOne(Yii::$app->request->get()['id']);
				$modal->tipe = Yii::$app->request->post()['tipe'];
				$modal->jumlah = Yii::$app->request->post()['jumlah'];
				$modal->deskripsi = Yii::$app->request->post()['deskripsi'];
				$modal->tanggal = "$tahun-$bulan-$tanggal";
				$modal->update();
				/*return $this->render('role_list');*/
				return $this->redirect(['accounting/kas-management']);
			}

        	return $this->render('update_kas');
        }else{
        	echo "You don't have access here";die;	
        }
	}

	public function actionDeleteKas(){
		if($this->isDeleteAllowed()){
			if(Yii::$app->request->get()){
				Kas::deleteAll('id_kas = '.Yii::$app->request->get()['id']);

				/*return $this->render('role_list');*/
				return $this->redirect(['accounting/kas-management']);
			}

        	return $this->render('list_kas');
        }else{
        	echo "You don't have access here";die;	
        }
	}

	/**
	*
	* TANAH
	*
	*/

	public function actionTanahManagement(){
		if($this->isSelectAllowed()){
			return $this->render('list_tanah');	
		}else{
			echo "You don't have access here";die;
		}
	}

	public function actionAddTanah(){
		if($this->isInsertAllowed()){
			if(Yii::$app->request->post()){

				$tanah = new Tanah();
				$tanah->no_tanah = Yii::$app->request->post()['no_tanah'];
				$tanah->luas = Yii::$app->request->post()['luas'];
				$tanah->harga = Yii::$app->request->post()['harga'];
				$tanah->lokasi = Yii::$app->request->post()['lokasi'];
				$tanah->status = Yii::$app->request->post()['status'];
				$tanah->deskripsi = Yii::$app->request->post()['deskripsi'];
				$tanah->save();
				/*return $this->render('role_list');*/
				return $this->redirect(['accounting/tanah-management']);
			}

        	return $this->render('add_tanah');
        }else{
        	echo "You don't have access here";die;	
        }
	}

	public function actionUpdateTanah(){
		if($this->isUpdateAllowed()){
			if(Yii::$app->request->post()){

				$tanah = Tanah::findOne(Yii::$app->request->get()['id']);
				$tanah->no_tanah = Yii::$app->request->post()['no_tanah'];
				$tanah->luas = Yii::$app->request->post()['luas'];
				$tanah->harga = Yii::$app->request->post()['harga'];
				$tanah->lokasi = Yii::$app->request->post()['lokasi'];
				$tanah->status = Yii::$app->request->post()['status'];
				$tanah->deskripsi = Yii::$app->request->post()['deskripsi'];
				$tanah->update();
				/*return $this->render('role_list');*/
				return $this->redirect(['accounting/tanah-management']);
			}

        	return $this->render('update_tanah');
        }else{
        	echo "You don't have access here";die;	
        }
	}

	public function actionDeleteTanah(){
		if($this->isDeleteAllowed()){
			if(Yii::$app->request->get()){
				Tanah::deleteAll('id_tanah = '.Yii::$app->request->get()['id']);

				/*return $this->render('role_list');*/
				return $this->redirect(['accounting/tanah-management']);
			}

        	return $this->render('list_tanah');
        }else{
        	echo "You don't have access here";die;	
        }
	}

	/**
	*
	* BANGUNAN
	*
	*/

	public function actionBangunanManagement(){
		if($this->isSelectAllowed()){
			return $this->render('list_bangunan');	
		}else{
			echo "You don't have access here";die;
		}
	}

	public function actionAddBangunan(){
		if($this->isInsertAllowed()){
			if(Yii::$app->request->post()){

				$bangunan = new Bangunan();
				$bangunan->no_bangunan = Yii::$app->request->post()['no_bangunan'];
				$bangunan->luas = Yii::$app->request->post()['luas'];
				$bangunan->harga = Yii::$app->request->post()['harga'];
				$bangunan->lokasi = Yii::$app->request->post()['lokasi'];
				$bangunan->status = Yii::$app->request->post()['status'];
				$bangunan->deskripsi = Yii::$app->request->post()['deskripsi'];
				$bangunan->save();
				/*return $this->render('role_list');*/
				return $this->redirect(['accounting/bangunan-management']);
			}

        	return $this->render('add_bangunan');
        }else{
        	echo "You don't have access here";die;	
        }
	}

	public function actionUpdateBangunan(){
		if($this->isUpdateAllowed()){
			if(Yii::$app->request->post()){

				$tanah = Bangunan::findOne(Yii::$app->request->get()['id']);
				$tanah->no_bangunan = Yii::$app->request->post()['no_bangunan'];
				$tanah->luas = Yii::$app->request->post()['luas'];
				$tanah->harga = Yii::$app->request->post()['harga'];
				$tanah->lokasi = Yii::$app->request->post()['lokasi'];
				$tanah->status = Yii::$app->request->post()['status'];
				$tanah->deskripsi = Yii::$app->request->post()['deskripsi'];
				$tanah->update();
				/*return $this->render('role_list');*/
				return $this->redirect(['accounting/bangunan-management']);
			}

        	return $this->render('update_bangunan');
        }else{
        	echo "You don't have access here";die;	
        }
	}

	public function actionDeleteBangunan(){
		if($this->isDeleteAllowed()){
			if(Yii::$app->request->get()){
				Bangunan::deleteAll('id_bangunan = '.Yii::$app->request->get()['id']);

				/*return $this->render('role_list');*/
				return $this->redirect(['accounting/bangunan-management']);
			}

        	return $this->render('list_bangunan');
        }else{
        	echo "You don't have access here";die;	
        }
	}

	/**
	*
	* NERACA
	*
	*/

	public function actionNeraca(){
		if($this->isSelectAllowed()){
			/*if(Yii::$app->request->post()){
				print_r(Yii::$app->request->post());die;
			}*/
			return $this->render('neraca');	
		}else{
			echo "You don't have access here";die;
		}
	}

	/**
	*
	* HUTANG
	*
	*/

	public function actionHutangManagement(){
		if($this->isSelectAllowed()){
			return $this->render('list_hutang');	
		}else{
			echo "You don't have access here";die;
		}
	}

	public function actionAddHutang(){
		if($this->isInsertAllowed()){
			if(Yii::$app->request->post()){

				list($bulan_hutang, $tanggal_hutang, $tahun_hutang) = explode("/", Yii::$app->request->post()['tanggal_hutang']);
				list($bulan_tempo, $tanggal_tempo, $tahun_tempo) = explode("/", Yii::$app->request->post()['jatuh_tempo']);

				$hutang = new Hutang();
				$hutang->nama_pemberi_pinjaman = Yii::$app->request->post()['nama_pemberi_pinjaman'];
				$hutang->jumlah_hutang = Yii::$app->request->post()['jumlah_hutang'];
				$hutang->tanggal_hutang = "$tahun_hutang-$bulan_hutang-$tanggal_hutang";
				$hutang->jatuh_tempo = "$tahun_tempo-$bulan_tempo-$tanggal_tempo";
				$hutang->deskripsi = Yii::$app->request->post()['deskripsi'];
				$hutang->save();
				/*return $this->render('role_list');*/

autocom/views/accounting/add_cicilan_hutang.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
?>
<div class="col-md-12">
    <div class="widget widget-green">
        <div class="widget-title">
            <div class="widget-controls">
				<a href="#" class="widget-control widget-control-full-screen" data-toggle="tooltip" data-placement="top" title="" data-original-title="Full Screen"><i class="fa fa-expand"></i></a>
				<a href="#" class="widget-control widget-control-full-screen widget-control-show-when-full" data-toggle="tooltip" data-placement="left" title="" data-original-title="Exit Full Screen"><i class="fa fa-expand"></i></a>
				<a href="#" class="widget-control widget-control-refresh" data-toggle="tooltip" data-placement="top" title="" data-original-title="Refresh"><i class="fa fa-refresh"></i></a>
				<a href="#" class="widget-control widget-control-minimize" data-toggle="tooltip" data-placement="top" title="" data-original-title="Minimize"><i class="fa fa-minus-circle"></i></a>
			</div>
            <h3><i class="fa fa-ok-circle"></i>Add new cicilan Hutang</h3>
        </div>
			<div class="widget-content">
				<div class="row">
					<div class="col-md-12">
						
						<?php $form = ActiveForm::begin([
							'id' => 'create-role-form',
							'options' => ['class' => 'form-horizontal', 'data-toggle'=>'validator', 'role'=>'form'],
							'fieldConfig' => [
							'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
							'labelOptions' => ['class' => 'col-lg-1 control-label'],
							],
						]); ?>

							<div class="form-group">
				                <label>Nominal</label>
				                <input type="number" class="form-control" placeholder="" name="nominal_dibayar" required = "required">
				           	</div>

				           	<div class="form-group">
				                <label>Tanggal Bayar</label>
				                <input type="text" placeholder="" class="form-control input-datepicker" name="tgl_transaksi" required = "required">
				           	</div>

							<?= Html::submitButton('Save', ['class' => 'btn btn-primary', 'name' => 'save-button']) ?>

						<?php ActiveForm::end(); ?>

					</div>
				</div>
			</div>
	</div>
</div>	

autocom/views/accounting/add_hutang.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
?>
<div class="col-md-12">
    <div class="widget widget-green">
        <div class="widget-title">
            <div class="widget-controls">
				<a href="#" class="widget-control widget-control-full-screen" data-toggle="tooltip" data-placement="top" title="" data-original-title="Full Screen"><i class="fa fa-expand"></i></a>
				<a href="#" class="widget-control widget-control-full-screen widget-control-show-when-full" data-toggle="tooltip" data-placement="left" title="" data-original-title="Exit Full Screen"><i class="fa fa-expand"></i></a>
				<a href="#" class="widget-control widget-control-refresh" data-toggle="tooltip" data-placement="top" title="" data-original-title="Refresh"><i class="fa fa-refresh"></i></a>
				<a href="#" class="widget-control widget-control-minimize" data-toggle="tooltip" data-placement="top" title="" data-original-title="Minimize"><i class="fa fa-minus-circle"></i></a>
			</div>
            <h3><i class="fa fa-ok-circle"></i>Add new Hutang</h3>
        </div>
			<div class="widget-content">
				<div class="row">
					<div class="col-md-12">
						
						<?php $form = ActiveForm::begin([
							'id' => 'create-role-form',
							'options' => ['class' => 'form-horizontal', 'data-toggle'=>'validator', 'role'=>'form'],
							'fieldConfig' => [
							'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
							'labelOptions' => ['class' => 'col-lg-1 control-label'],
							],
						]); ?>

							<div class="form-group">
				                <label>Nama Pemberi Pinjaman</label>
				                <input type="text" class="form-control" placeholder="" name="nama_pemberi_pinjaman" required = "required">
				           	</div>

							<div class="form-group">
				                <label>Jumlah Hutang</label>
				                <input type="number" class="form-control" placeholder="" name="jumlah_hutang" required = "required">
				           	</div>

				           	<div class="form-group">
				                <label>Tanggal Hutang</label>
				                <input type="text" placeholder="" class="form-control input-datepicker" name="tanggal_hutang" required = "required">
				           	</div>

				           	<div class="form-group">
				                <label>Jatuh Tempo</label>
				                <input type="text" placeholder="" class="form-control input-datepicker" name="jatuh_tempo" required = "required">
				           	</div>
							
							<div class="form-group">
				                <label>Description</label>
				                <textarea class="form-control" placeholder="" name="deskripsi" required = "required"></textarea>
				           	</div>

							<?= Html::submitButton('Save', ['class' => 'btn btn-primary', 'name' => 'save-button']) ?>

						<?php ActiveForm::end(); ?>

					</div>
				</div>
			</div>
	</div>
</div>	

autocom/views/accounting/add_modal.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
?>
<div class="col-md-12">
    <div class="widget widget-green">
        <div class="widget-title">
            <div class="widget-controls">
				<a href="#" class="widget-control widget-control-full-screen" data-toggle="tooltip" data-placement="top" title="" data-original-title="Full Screen"><i class="fa fa-expand"></i></a>
				<a href="#" class="widget-control widget-control-full-screen widget-control-show-when-full" data-toggle="tooltip" data-placement="left" title="" data-original-title="Exit Full Screen"><i class="fa fa-expand"></i></a>
				<a href="#" class="widget-control widget-control-refresh" data-toggle="tooltip" data-placement="top" title="" data-original-title="Refresh"><i class="fa fa-refresh"></i></a>
				<a href="#" class="widget-control widget-control-minimize" data-toggle="tooltip" data-placement="top" title="" data-original-title="Minimize"><i class="fa fa-minus-circle"></i></a>
			</div>
            <h3><i class="fa fa-ok-circle"></i>Add new modale</h3>
        </div>
			<div class="widget-content">
				<div class="row">
					<div class="col-md-12">
						
						<?php $form = ActiveForm::begin([
							'id' => 'create-role-form',
							'options' => ['class' => 'form-horizontal', 'data-toggle'=>'validator', 'role'=>'form'],
							'fieldConfig' => [
							'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
							'labelOptions' => ['class' => 'col-lg-1 control-label'],
							],
						]); ?>
							<div class="form-group">
				                <label>Quantity</label>
				                <input type="number" class="form-control" placeholder="" name="jumlah" required = "required">
				           	</div>
							
							<div class="form-group">
				                <label>Description</label>
				                <textarea class="form-control" placeholder="" name="keterangan" required = "required"></textarea>
				           	</div>

				           	<div class="form-group">
				                <label>Date</label>
				                <input type="text" placeholder="" class="form-control input-datepicker" name="tanggal" required = "required">
				           	</div>

							<?= Html::submitButton('Save', ['class' => 'btn btn-primary', 'name' => 'save-button']) ?>

						<?php ActiveForm::end(); ?>

					</div>
				</div>
			</div>
	</div>
</div>	

autocom/views/accounting/index.php
welcome to accounting module:)

autocom/views/accounting/list_hutang.php
<?php
use yii\helpers\Html;

use app\models\Hutang;
use app\models\TransaksiHp;

$kas = Hutang::find()->asArray()->all();
$transaksi = new TransaksiHp();
?>

<div class="col-md-12">
    <div class="widget widget-green">
        <div class="widget-title">
            <div class="widget-controls">
				<a href="#" class="widget-control widget-control-full-screen" data-toggle="tooltip" data-placement="top" title="" data-original-title="Full Screen"><i class="fa fa-expand"></i></a>
				<a href="#" class="widget-control widget-control-full-screen widget-control-show-when-full" data-toggle="tooltip" data-placement="left" title="" data-original-title="Exit Full Screen"><i class="fa fa-expand"></i></a>
				<a href="#" class="widget-control widget-control-refresh" data-toggle="tooltip" data-placement="top" title="" data-original-title="Refresh"><i class="fa fa-refresh"></i></a>
				<a href="#" class="widget-control widget-control-minimize" data-toggle="tooltip" data-placement="top" title="" data-original-title="Minimize"><i class="fa fa-minus-circle"></i></a>
			</div>
            <h3><i class="fa fa-ok-circle"></i>list of Hutang</h3>
        </div>
			<div class="widget-content">
				<div class="row">
					<div class="col-md-12">
						<a href="<?= Yii::$app->urlManager->createUrl(['accounting/add-hutang'])?>" class="btn btn-success btn-sm"><i class="glyphicon glyphicon-plus"></i></a>
						<table class="table">
							<thead>
								<tr>
									<th>No</th>
									<th>Nama Pemberi Pinjaman</th>
									<th>Jumlah Hutang</th>
									<th>Sisa Hutang</th>
									<th>Tanggal Hutang</th>
									<th>Jatuh Tempo</th>
									<th>Deskripsi</th>
									<th width="150px">Action</th>
								</tr>
							</thead>
							<tbody>
								<?php 
									$i=1; foreach ( $kas as $key => $value) {
								?>
									<tr>
										<td><?=$i?></td>
										<td><?=$value['nama_pemberi_pinjaman']?></td>
										<td><?=$value['jumlah_hutang']?></td>
										<td>
											<?php
												$dibayar = $transaksi->getTotalCicilanHutang($value['id_hutang']);
												if(!empty($dibayar)){
													echo (floatval($value['jumlah_hutang']) - floatval($dibayar['dibayar']));
												}else{
													echo $value['jumlah_hutang'];
												}
											?>
										</td>
										<td><?=$value['tanggal_hutang']?></td>
										<td><?=$value['jatuh_tempo']?></td>
										<td><?=$value['deskripsi']?></td>
										<td>
											
											<a href="<?= Yii::$app->urlManager->createUrl(['accounting/update-hutang',"id"=>$value['id_hutang']])?>" class="btn btn-primary btn-sm"><i class="glyphicon glyphicon-pencil"></i></a>
											
											<a href="<?= Yii::$app->urlManager->createUrl(['accounting/delete-hutang',"id"=>$value['id_hutang']])?>" class="btn btn-danger btn-sm"><i class="glyphicon glyphicon-trash"></i></a>

											<a href="<?= Yii::$app->urlManager->createUrl(['accounting/cicilan-hutang',"id"=>$value['id_hutang']])?>" class="btn btn-primary btn-sm"><i class="glyphicon glyphicon-pencil"></i></a>
										</td>
									</tr>
								<?php $i++; } ?>
							</tbody>
						</table>
					</div>
				</div>
			</div>
	</div>
</div>

autocom/views/accounting/list_kas.php
<?php
use yii\helpers\Html;

use app\models\Kas;

$kas = Kas::find()->asArray()->all();
?>

<div class="col-md-12">
    <div class="widget widget-green">
        <div class="widget-title">
            <div class="widget-controls">
				<a href="#" class="widget-control widget-control-full-screen" data-toggle="tooltip" data-placement="top" title="" data-original-title="Full Screen"><i class="fa fa-expand"></i></a>
				<a href="#" class="widget-control widget-control-full-screen widget-control-show-when-full" data-toggle="tooltip" data-placement="left" title="" data-original-title="Exit Full Screen"><i class="fa fa-expand"></i></a>
				<a href="#" class="widget-control widget-control-refresh" data-toggle="tooltip" data-placement="top" title="" data-original-title="Refresh"><i class="fa fa-refresh"></i></a>
				<a href="#" class="widget-control widget-control-minimize" data-toggle="tooltip" data-placement="top" title="" data-original-title="Minimize"><i class="fa fa-minus-circle"></i></a>
			</div>
            <h3><i class="fa fa-ok-circle"></i>list of Kas</h3>
        </div>
			<div class="widget-content">
				<div class="row">
					<div class="col-md-12">
						<a href="<?= Yii::$app->urlManager->createUrl(['accounting/add-kas'])?>" class="btn btn-success btn-sm"><i class="glyphicon glyphicon-plus"></i></a>
						<table class="table">
							<thead>
								<tr>
									<th>No</th>
									<th>Type</th>
									<th>Quantity</th>
									<th>Date Accur</th>
									<th>Description</th>
									<th width="150px">Action</th>
								</tr>
							</thead>
							<tbody>
								<?php 
									$i=1; foreach ( $kas as $key => $value) {
									$tipe = "";
									if(intval($value['tipe'])==1){
										$tipe = "Income";
									}else{
										$tipe = "Outcome";
									}
								?>
									<tr>
										<td><?=$i?></td>
										<td><?=$tipe?></td>
										<td><?=$value['jumlah']?></td>
										<td><?=$value['deskripsi']?></td>
										<td><?=$value['tanggal']?></td>
										<td>
											
											<a href="<?= Yii::$app->urlManager->createUrl(['accounting/update-kas',"id"=>$value['id_kas']])?>" class="btn btn-primary btn-sm"><i class="glyphicon glyphicon-pencil"></i></a>
											
											<a href="<?= Yii::$app->urlManager->createUrl(['accounting/delete-kas',"id"=>$value['id_kas']])?>" class="btn btn-danger btn-sm"><i class="glyphicon glyphicon-trash"></i></a>
										</td>
									</tr>
								<?php $i++; } ?>
							</tbody>
						</table>
					</div>
				</div>
			</div>
	</div>
</div>

autocom/views/accounting/list_tanah.php
<?php
use yii\helpers\Html;

use app\models\Tanah;

$tanah = Tanah::find()->asArray()->all();
?>

<div class="col-md-12">
    <div class="widget widget-green">
        <div class="widget-title">
            <div class="widget-controls">
				<a href="#" class="widget-control widget-control-full-screen" data-toggle="tooltip" data-placement="top" title="" data-original-title="Full Screen"><i class="fa fa-expand"></i></a>
				<a href="#" class="widget-control widget-control-full-screen widget-control-show-when-full" data-toggle="tooltip" data-placement="left" title="" data-original-title="Exit Full Screen"><i class="fa fa-expand"></i></a>
				<a href="#" class="widget-control widget-control-refresh" data-toggle="tooltip" data-placement="top" title="" data-original-title="Refresh"><i class="fa fa-refresh"></i></a>
				<a href="#" class="widget-control widget-control-minimize" data-toggle="tooltip" data-placement="top" title="" data-original-title="Minimize"><i class="fa fa-minus-circle"></i></a>
			</div>
            <h3><i class="fa fa-ok-circle"></i>list of Kas</h3>
        </div>
			<div class="widget-content">
				<div class="row">
					<div class="col-md-12">
						<a href="<?= Yii::$app->urlManager->createUrl(['accounting/add-tanah'])?>" class="btn btn-success btn-sm"><i class="glyphicon glyphicon-plus"></i></a>
						<table class="table">
							<thead>
								<tr>
									<th>No</th>
									<th>No Tanah</th>
									<th>Luas</th>
									<th>Harga</th>
									<th>Lokasi</th>
									<th>Status</th>
									<th>Deskripsi</th>
									<th width="150px">Action</th>
								</tr>
							</thead>
							<tbody>
								<?php 
									$i=1; foreach ( $tanah as $key => $value) {
								?>
									<tr>
										<td><?=$i?></td>
										<td><?=$value['no_tanah']?></td>
										<td><?=$value['luas']?></td>
										<td><?=$value['harga']?></td>
										<td><?=$value['lokasi']?></td>
										<td><?=$value['status']?></td>
										<td><?=$value['deskripsi']?></td>
										<td>
											
											<a href="<?= Yii::$app->urlManager->createUrl(['accounting/update-tanah',"id"=>$value['id_tanah']])?>" class="btn btn-primary btn-sm"><i class="glyphicon glyphicon-pencil"></i></a>
											
											<a href="<?= Yii::$app->urlManager->createUrl(['accounting/delete-tanah',"id"=>$value['id_tanah']])?>" class="btn btn-danger btn-sm"><i class="glyphicon glyphicon-trash"></i></a>
										</td>
									</tr>
								<?php $i++; } ?>
							</tbody>
						</table>
					</div>
				</div>
			</div>
	</div>
</div>