autocom/controllers/SuratArsipController.php
<?php

namespace app\controllers;

use Yii;
use app\controllers\SecureController;
use mPDF;
use app\models\Surat;

class SuratArsipController extends SecureController{

	public $layout = "suratarsip_layout";
//	public $data = new Surat();

	public function actionIndex() {
		return $this->render('index');

//		$mpdf = new mPDF;
//		$mpdf->WriteHTML('<p>Hallo World</p>');
//		$mpdf->Output();
	}

	// Membuat surat
	public function actionBuatSurat(){
		if($this->isInsertAllowed()){
			if(Yii::$app->request->post()){
				$suratModel = new Surat();
				$suratModel->insertSurat(Yii::$app->request->post()['Surat']);
				echo "berhasil";
			}
			return $this->render('buat_surat');
		}else{
			echo "You don't have access here";die;
		}
	}

	// Melihat surat masuk
	public function actionSuratMasuk(){
		if($this->isSelectAllowed()){
			return $this->render('surat_masuk');
		}else{
			echo "You don't have access here";die;
		}
	}

	// Melihat surat keluar
	public function actionSuratKeluar(){
		if($this->isSelectAllowed()){
			return $this->render('surat_keluar');
		}else{
			echo "You don't have access here";die;
		}
	}

	// Fitur persetujuan surat untuk manajer
	public function actionPersetujuanSurat(){
		if($this->isSelectAllowed()){
			return $this->render('persetujuan_surat');
		}else{
			echo "You don't have access here";die;
		}
	}

	// Melihat memo masuk dan terdapat tombol Buat Memo
	public function actionMemoMasuk(){
		if($this->isSelectAllowed()){
			return $this->render('memo_masuk');
		}else{
			echo "You don't have access here";die;
		}
	}

	// Membuat memo
	public function actionBuatMemo(){
		if($this->isSelectAllowed()){
			return $this->render('buat_memo');
		}else{
			echo "You don't have access here";die;
		}
	}

	// Melihat memo masuk dan terdapat tombol Buat Memo
	public function actionMemoKeluar(){
		if($this->isSelectAllowed()){
			return $this->render('memo_keluar');
		}else{
			echo "You don't have access here";die;
		}
	}

	// Melihat daftar arsip sesuai user rule
	public function actionArsip(){
		if($this->isSelectAllowed()){
			return $this->render('arsip');
		}else{
			echo "You don't have access here";die;
		}
	}

	// Membuat arsip
	public function actionBuatArsip(){
		if($this->isSelectAllowed()){
			return $this->render('buat_arsip');
		}else{
			echo "You don't have access here";die;
		}
	}

	public function actionDelete($id){
		if($this->isDeleteAllowed()){
			if(Yii::$app->request->get()){
				Surat::deleteAll('nomor_surat='.Yii::$app->request->get()['id'] );
				$this->redirect('surat-masuk');
			}
		}
	}

	public function actionPrint(){
		if($this->isSelectAllowed()){
			$mpdf = new mPDF;
			$mpdf->WriteHTML($this->renderPartial('printsurat'));
			$mpdf->Output();
		}else{
			echo "You don't have access here";die;
		}
	}
}

?>

autocom/views/surat-arsip/arsip.php
<?php
use yii\helpers\Html;
?>

<?= Html::a("Buat Arsip", Yii::$app->urlManager->createUrl(['surat-arsip/buat-arsip']), ["class"=>["btn","btn-primary"]])?>

<br> Melihat daftar arsip

autocom/views/surat-arsip/buat_arsip.php
membuat

autocom/views/surat-arsip/buat_memo.php
Membuat memo

autocom/views/surat-arsip/buat_surat.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use app\models\Surat;

$model = new Surat();

$form = ActiveForm::begin([
    'id' => 'buatsurat',
    'options' => ['class' => 'form'],
]) ?>

<?= $form->field($model, 'nomor_surat') ?>
<?php // $form->field($model, 'id_jenis_surat') ?>

<div class="form-group field-surat-id_jenis_surat required">
    <label class="control-label" for="surat-id_jenis_surat">Jenis Surat</label>
<!--    <input type="text" value="--><?php //echo date("Y-m-d") ?><!--" id="surat-tanggal_surat" class="form-control" name="Surat[tanggal_surat]">-->
    <select id="surat-id_jenis_surat" name="Surat[id_jenis_surat]">
        <option>Pilih</option>
        <?php

        foreach( $model -> showjenissurat() as $item => $value){
            echo "<option value=".$value['id_jenis_surat'].">".$value['nama_jenis_surat']."</option>";
        }

        ?>
    </select>
</div>

<?= $form->field($model, 'id_pengirim') ?>
<div class="form-group field-surat-tanggal_surat required">
    <label class="control-label" for="surat-tanggal_surat">Tanggal Surat</label>
    <input type="text" value="<?php echo date("Y-m-d") ?>" id="surat-tanggal_surat" class="form-control" name="Surat[tanggal_surat]">
</div>
<?= $form->field($model, 'perihal') ?>
<?= $form->field($model, 'isi_surat') ?>

<?= Html::submitButton('Simpan', ['class' => 'btn btn-success', 'name' => 'send-button ' ]) ?>

<?php
    ActiveForm::end()
?>

autocom/views/surat-arsip/index.php
Welcome to surat arsip module :)

autocom/views/surat-arsip/memo_keluar.php
Melihat daftar memo keluar

autocom/views/surat-arsip/memo_masuk.php
<?php
use yii\helpers\Html;
?>

<?= Html::a("Buat Memo", Yii::$app->urlManager->createUrl(['surat-arsip/buat-memo']), ["class"=>["btn","btn-primary"]])?>
<br> Melihat daftar memo masuk

autocom/views/surat-arsip/persetujuan_surat.php
Melihat daftar surat yang harus disetujui untuk manajer

autocom/views/surat-arsip/printsurat.php
<?php

use app\models\Surat;

$surat = new Surat();

$id = Yii::$app->request->get()['id'];

echo $id;

foreach ($surat -> detailSurat($id) as $item => $value){
    echo "<tr>";
    echo "<td>".$value['nomor_surat']."</td>";
    echo "<td>".$value['id_jenis_surat']."</td>";
    echo "<td>".$value['id_pengirim']."</td>";
    echo "<td>".$value['tanggal_surat']."</td>";
    echo "<td>".$value['perihal']."</td>";
    echo "<td>".$value['isi_surat']."</td>";
    echo "</tr>";
}

?>

autocom/views/surat-arsip/surat_keluar.php
Melihat daftar surat keluar

autocom/views/surat-arsip/surat_masuk.php
<?php

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use app\models\Surat;

$datasurat = new Surat();

?>
<div class="widget widget-blue">
    <div class="widget-title">
        Surat Masuk
    </div>
<div class="widget-content">
    <div class="row">
        <div class="col-md-12">
    <table class="table">
        <tr>
            <th>Nomor Surat</th>
            <th>Jenis Surat</th>
            <th>Pengirim</th>
            <th>Tanggal</th>
            <th>Perihal</th>
            <th>Isi</th>
            <th>Action</th>
        </tr>
    <?php
        foreach( $datasurat -> showalldata() as $item => $value){
            echo "<tr>";
            echo "<td>".$value['nomor_surat']."</td>";
            echo "<td>".$value['id_jenis_surat']."</td>";
            echo "<td>".$value['id_pengirim']."</td>";
            echo "<td>".$value['tanggal_surat']."</td>";
            echo "<td>".$value['perihal']."</td>";
            echo "<td>".$value['isi_surat']."</td>";
            echo "<td>".Html::a("Delete", Yii::$app->urlManager->createUrl(["surat-arsip/delete", "id"=>$value["nomor_surat"]]),[])." | ".
                Html::a("Print", Yii::$app->urlManager->createUrl(["surat-arsip/print", "id"=>$value["nomor_surat"]]),[])
                ."</td>";
            echo "</tr>";
        }
    ?>
    </table>
            </div>
        </div>
    </div>
    </div>