autocom/controllers/WarehouseController.php
<?php

namespace app\controllers;

use Yii;
use app\controllers\SecureController;
use app\models\User;
use app\models\WUsers;

class WarehouseController extends SecureController{
	public $layout = "warehouse_layout";

	
	public function actionIndex(){
		$status = WUsers::findOne($_SESSION['__id']);
		$status = $status['unlocked'];
		if ($status==0) {
			return "Anda tidak mendapatkan hak akses<br>Hubungi Admin Warehouse";
			exit(0);
		}
		// print_r($_SESSION);
		return $this->render('index');
	}

	public function actionUsername()
	{
		$user = User::find()->where(['id'=>'17'])->asArray()->one();
		return $user['username'];
		return ;
	}
	public function actionCreate_organisasibarang(){
			return $this->render('create_organisasibarang');	
	}
	public function actionCreate_datasupplier(){
			return $this->render('create_datasupplier');	
	}
	public function actionUsers(){
			return $this->render('user_list');	
	}
	public function actionOrganisasibarang(){
		return $this->render('OrganisasiBarang');
	}
	public function actionDatasupplier(){
		return $this->render('DataSupplier');
	}
	public function actionPenjualan(){
		return $this->render('penjualan');
	}


	public function actionCreate_datapembelian(){
		return $this->render('create_datapembelian');
	}
	
	public function actionCreate_datapenjualan(){
		return $this->render('create_datapenjualan');
	}


	public function actionPembelian(){
		return $this->render('pembelian');
	}

	public function actionBarang(){
		return $this->render('barang');
	}

	public function actionKategoriBarang(){
		return $this->render('kategori_barang');
	}

	public function actionLaporan(){
		return $this->render('laporan');
	}


	public function actionCreateUser(){
		if($this->isInsertAllowed()){
			if(Yii::$app->request->post()){
				$new_user = new User();
				$cek_uname = $new_user->findUsernameExists(Yii::$app->request->post()['username']);
				if ($cek_uname==null) {
					
					$new_user->saveBySQL(Yii::$app->request->post());
					$w_user = new WUsers();
					$w_user->saveBySQL(Yii::$app->request->post());

					return $this->redirect(['warehouse/users']);
				}else{
					print_r($cek_uname);
					return 'Username sudah terpakai';
				}

			}

        	return $this->render('create_user');
        }else{
        	echo "You don't have access here";die;	
        }
	}

		public function actionUpdateUser(){
		if($this->isUpdateAllowed()){
			if(Yii::$app->request->post()){
				$user = User::findOne(Yii::$app->request->get()['id']);
				$user->username = Yii::$app->request->post()['username'];
		        $user->email = Yii::$app->request->post()['email'];
		        $user->sec_question = Yii::$app->request->post()['sec_question'];
		        $user->sec_answer = Yii::$app->request->post()['sec_answer'];
		        $user->user_type = Yii::$app->request->post()['user_type'];
		        $user->authKey = "";
		        $user->accessToken = "";
		        $user->update();

				/*return $this->render('user_list');*/
				return $this->redirect(['warehouse/user-management']);
			}

        	return $this->render('update_user');
        }else{
        	echo "You don't have access here";die;	
        }
	}

	public function actionDeleteUser(){
		if($this->isDeleteAllowed()){
			if(Yii::$app->request->get()){
				User::deleteAll('id = '.Yii::$app->request->get()['id']);

				/*return $this->render('user_list');*/
				return $this->redirect(['warehouse/user-management']);
			}

        	return $this->render('user_list');
        }else{
        	echo "You don't have access here";die;	
        }
	}

	public function actionUpdatelock($id_user, $status)
	{
		
			if(Yii::$app->request->get()){}
	}

}

?>

autocom/views/warehouse/DataSupplier.php
<?php
use yii\helpers\Html;

use app\models\User;

$model = new User();
?>



<div class="col-md-12">
    <div class="widget widget-green">
        <div class="widget-title">
            <div class="widget-controls">
				<a href="#" class="widget-control widget-control-full-screen" data-toggle="tooltip" data-placement="top" title="" data-original-title="Full Screen"><i class="fa fa-expand"></i></a>
				<a href="#" class="widget-control widget-control-full-screen widget-control-show-when-full" data-toggle="tooltip" data-placement="left" title="" data-original-title="Exit Full Screen"><i class="fa fa-expand"></i></a>
				<a href="#" class="widget-control widget-control-refresh" data-toggle="tooltip" data-placement="top" title="" data-original-title="Refresh"><i class="fa fa-refresh"></i></a>
				<a href="#" class="widget-control widget-control-minimize" data-toggle="tooltip" data-placement="top" title="" data-original-title="Minimize"><i class="fa fa-minus-circle"></i></a>
			</div>
            <h3><i class="fa fa-ok-circle"></i>Data Supplier</h3>
        </div>
			<div class="widget-content">
				<div class="row">
					<div class="col-md-12">
						<a href="<?= Yii::$app->urlManager->createUrl(['warehouse/create_datasupplier']) ?>" class="btn btn-success btn-sm"><i class="glyphicon glyphicon-plus"></i></a>
						<table class="table">
							<thead>
								<tr>
									<th>ID</th>
									<th>Nama</th>
									<th>Alamat</th>
									<th>Contact Person</th>
									<th width="150px">Action</th>
								</tr>
							</thead>
							<tbody>
								<?php $i=1;// foreach ( $model->findUser() as $key => $value) { ?>
									<tr>
									</tr>
								<?php// $i++; } ?>
							</tbody>
						</table>
					</div>
				</div>
			</div>
	</div>
</div>	

<!--
-->

<!-- 
<?= Html::a("Create new datasupplier", Yii::$app->urlManager->createUrl(['warehouse/create_datasupplier']), ["class"=>["btn","btn-primary"]])?>
<table border = "1" style="border-collapse:collapse">
	<tr>
		<th>No</th>
		<th>Username</th>
		<th>Email</th>
		<th>User type</th>
		<th>Action</th>
	</tr>
<?php $i=1; foreach ( $model->findUser() as $key => $value) { ?>
	<tr>
		<td><?=$i?></td>
		<td><?=$value['username']?></td>
		<td><?=$value['email']?></td>
		<td><?=$value['user_type_name']?></td>
		<td>
			<?= Html::a("edit", Yii::$app->urlManager->createUrl(['security/update-user',"id"=>$value['id']]), [])?> | 
			<?= Html::a("delete", Yii::$app->urlManager->createUrl(['security/delete-user',"id"=>$value['id']]),[])?>
		</td>
	</tr>
<?php $i++; } ?>
</table>
 -->

autocom/views/warehouse/OrganisasiBarang.php
<?php
use yii\helpers\Html;

use app\models\User;

$model = new User();
?>



<div class="col-md-12">
    <div class="widget widget-green">
        <div class="widget-title">
            <div class="widget-controls">
				<a href="#" class="widget-control widget-control-full-screen" data-toggle="tooltip" data-placement="top" title="" data-original-title="Full Screen"><i class="fa fa-expand"></i></a>
				<a href="#" class="widget-control widget-control-full-screen widget-control-show-when-full" data-toggle="tooltip" data-placement="left" title="" data-original-title="Exit Full Screen"><i class="fa fa-expand"></i></a>
				<a href="#" class="widget-control widget-control-refresh" data-toggle="tooltip" data-placement="top" title="" data-original-title="Refresh"><i class="fa fa-refresh"></i></a>
				<a href="#" class="widget-control widget-control-minimize" data-toggle="tooltip" data-placement="top" title="" data-original-title="Minimize"><i class="fa fa-minus-circle"></i></a>
			</div>
            <h3><i class="fa fa-ok-circle"></i>Organisasi Barang</h3>
        </div>
			<div class="widget-content">
				<div class="row">
					<div class="col-md-12">
						<a href="<?= Yii::$app->urlManager->createUrl(['warehouse/create_organisasibarang']) ?>" class="btn btn-success btn-sm"><i class="glyphicon glyphicon-plus"></i></a>
						<table class="table">
							<thead>
								<tr>
									<th>ID</th>
									<th>Nama Barang</th>
									<th>Jumlah Barang</th>
									<th>Tanggal Pembelian</th>
									<th width="150px">Action</th>
								</tr>
							</thead>
							<tbody>
								<?php $i=1; foreach ( $model->findUser() as $key => $value) { 
									if ($value['user_type_name'] =='admin warehouse'
										||  $value['user_type_name'] =='kepala gudang warehouse'
										||  $value['user_type_name'] =='supervisor warehouse'
										||  $value['user_type_name'] =='operator warehouse'
										) {
										# code...
									
									?>
									<tr>
										<td><?=$i?></td>
										<td><?=$value['username']?></td>
										<td><?=$value['email']?></td>
										<td><?=$value['user_type_name']?></td>
										<td>
											
											<a href="<?= Yii::$app->urlManager->createUrl(['security/update-user',"id"=>$value['id']])?>" class="btn btn-primary btn-sm"><i class="glyphicon glyphicon-pencil"></i></a>
											
											<a href="<?= Yii::$app->urlManager->createUrl(['security/delete-user',"id"=>$value['id']])?>" class="btn btn-danger btn-sm"><i class="glyphicon glyphicon-trash"></i></a>
										</td>
									</tr>
								<?php $i++;} } ?>
							</tbody>
						</table>
					</div>
				</div>
			</div>
	</div>
</div>	



<!-- 
<?= Html::a("Create new user", Yii::$app->urlManager->createUrl(['security/create-user']), ["class"=>["btn","btn-primary"]])?>
<table border = "1" style="border-collapse:collapse">
	<tr>
		<th>No</th>
		<th>Username</th>
		<th>Email</th>
		<th>User type</th>
		<th>Action</th>
	</tr>
<?php $i=1; foreach ( $model->findUser() as $key => $value) { ?>
	<tr>
		<td><?=$i?></td>
		<td><?=$value['username']?></td>
		<td><?=$value['email']?></td>
		<td><?=$value['user_type_name']?></td>
		<td>
			<?= Html::a("edit", Yii::$app->urlManager->createUrl(['security/update-user',"id"=>$value['id']]), [])?> | 
			<?= Html::a("delete", Yii::$app->urlManager->createUrl(['security/delete-user',"id"=>$value['id']]),[])?>
		</td>
	</tr>
<?php $i++; } ?>
</table>
 -->

autocom/views/warehouse/barang.php
<?php
use yii\helpers\Html;

use app\models\User;

$model = new User();
?>



<div class="col-md-12">
    <div class="widget widget-green">
        <div class="widget-title">
            <div class="widget-controls">
				<a href="#" class="widget-control widget-control-full-screen" data-toggle="tooltip" data-placement="top" title="" data-original-title="Full Screen"><i class="fa fa-expand"></i></a>
				<a href="#" class="widget-control widget-control-full-screen widget-control-show-when-full" data-toggle="tooltip" data-placement="left" title="" data-original-title="Exit Full Screen"><i class="fa fa-expand"></i></a>
				<a href="#" class="widget-control widget-control-refresh" data-toggle="tooltip" data-placement="top" title="" data-original-title="Refresh"><i class="fa fa-refresh"></i></a>
				<a href="#" class="widget-control widget-control-minimize" data-toggle="tooltip" data-placement="top" title="" data-original-title="Minimize"><i class="fa fa-minus-circle"></i></a>
			</div>
            <h3><i class="fa fa-ok-circle"></i>Data penjualan</h3>
        </div>
			<div class="widget-content">
				<div class="row">
					<div class="col-md-12">
						<a href="<?= Yii::$app->urlManager->createUrl(['security/create-user']) ?>" class="btn btn-success btn-sm"><i class="glyphicon glyphicon-plus"></i></a>
						<table class="table">
							<thead>
								<tr>
									<th>No</th>
									<th>Tanggal</th>
									<th>Barang</th>
									<th>Jumlah</th>
									<th>Laba</th>
									<th width="150px">Action</th>
								</tr>
							</thead>
							<tbody>
								<?php $i=1;// foreach ( $model->findUser() as $key => $value) { ?>
									<tr>
									</tr>
								<?php// $i++; } ?>
							</tbody>
						</table>
					</div>
				</div>
			</div>
	</div>
</div>	

autocom/views/warehouse/create_datapembelian.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

use app\models\UserType;
?>



<div class="col-md-12">
    <div class="widget widget-green">
        <div class="widget-title">
            <div class="widget-controls">
				<a href="#" class="widget-control widget-control-full-screen" data-toggle="tooltip" data-placement="top" title="" data-original-title="Full Screen"><i class="fa fa-expand"></i></a>
				<a href="#" class="widget-control widget-control-full-screen widget-control-show-when-full" data-toggle="tooltip" data-placement="left" title="" data-original-title="Exit Full Screen"><i class="fa fa-expand"></i></a>
				<a href="#" class="widget-control widget-control-refresh" data-toggle="tooltip" data-placement="top" title="" data-original-title="Refresh"><i class="fa fa-refresh"></i></a>
				<a href="#" class="widget-control widget-control-minimize" data-toggle="tooltip" data-placement="top" title="" data-original-title="Minimize"><i class="fa fa-minus-circle"></i></a>
			</div>
            <h3><i class="fa fa-ok-circle"></i>create new data pembelian</h3>
        </div>
			<div class="widget-content">
				<div class="row">
					<div class="col-md-12">
						
						<?php $form = ActiveForm::begin([
							'id' => 'create-role-form',
							'options' => ['class' => 'form-horizontal', 'data-toggle'=>'validator', 'role'=>'form'],
							'fieldConfig' => [
							'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
							'labelOptions' => ['class' => 'col-lg-1 control-label'],
							],
						]); ?>

								<div class="form-group">
									<label>No Nota</label>
									<?= Html::input("text", "no nota", null, ["placeholder"=>"No Nota", "required"=>"required", "class"=>"form-control"]) ?>
								</div>

								<div class="form-group">
									<label>Kode Pemasok</label>
									<?= Html::input("text", "kode pemasok", null, ["placeholder"=>"Kode Pemasok", "required"=>"required", "class"=>"form-control"]) ?>
								</div>

								<div class="form-group">
									<label>Tanggal</label>
									<?= Html::input("text", "tanggal", null, ["placeholder"=>"Tanggal", "required"=>"required", "class"=>"form-control"]) ?>
								</div>

								<div class="form-group">
									<label>Harga Satuan</label>
									<?= Html::input("text", "harga satuan", null, ["placeholder"=>"Harga Satuan", "required"=>"required", "class"=>"form-control"]) ?>
								</div>

								<div class="form-group">
									<label>Jumlah</label>
									<?= Html::input("text", "jumlah", null, ["placeholder"=>"Jumlah", "required"=>"required", "class"=>"form-control"]) ?>
								</div>

								<?= Html::submitButton('Save', ['class' => 'btn btn-primary']) ?>

						<?php ActiveForm::end(); ?>

					</div>
				</div>
			</div>
	</div>
</div>	


<!-- 
<h3>Create new user type</h3>
<?php $form = ActiveForm::begin([
	'id' => 'create-user-type-form',
	'options' => ['class' => 'form-horizontal', 'data-toggle'=>'validator'],
	'fieldConfig' => [
	'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
	'labelOptions' => ['class' => 'col-lg-1 control-label'],
	],
]); ?>

	<div class="form-group">
		<div class="col-lg-offset-1 col-lg-11">
			<?= Html::input("text", "id", null, ["placeholder"=>"ID", "required"=>"required"]) ?>
		</div>
	</div>

	<div class="form-group">
		<div class="col-lg-offset-1 col-lg-11">
			<?= Html::input("text", "username", null, ["placeholder"=>"Username", "required"=>"required"]) ?>
		</div>
	</div>

	<div class="form-group">
		<div class="col-lg-offset-1 col-lg-11">
			<?= Html::input("text", "alamat", null, ["placeholder"=>"Alamat", "required"=>"required"]) ?>
		</div>
	</div>

	<div class="form-group">
		<div class="col-lg-offset-1 col-lg-11">
			<?= Html::input("text", "sec_question", "nama project?", ["required"=>"required"]) ?>
		</div>
	</div>

	<div class="form-group">
		<div class="col-lg-offset-1 col-lg-11">
			<?= Html::input("text", "sec_answer", "autocom", ["required"=>"required"]) ?>
		</div>
	</div>

	<label>User type will be attached</label>

	<div class="form-group">
		<div class="col-lg-offset-1 col-lg-11">
			<ul>
			<?php
				foreach (UserType::find()->asArray()->all() as $key => $value) {
					echo "<li>";
						echo Html::radio("user_type", false, ["label"=>$value["name"], "value"=>$value["id"]]);
					echo "</li>";
				}
			?>
			</ul>
		</div>
	</div>

	<div class="form-group">
		<div class="col-lg-offset-1 col-lg-11">
			<?= Html::submitButton('Save', ['class' => 'btn btn-primary']) ?>
		</div>
	</div>

<?php ActiveForm::end(); ?>
 -->

autocom/views/warehouse/create_datapenjualan.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

use app\models\UserType;
?>



<div class="col-md-12">
    <div class="widget widget-green">
        <div class="widget-title">
            <div class="widget-controls">
				<a href="#" class="widget-control widget-control-full-screen" data-toggle="tooltip" data-placement="top" title="" data-original-title="Full Screen"><i class="fa fa-expand"></i></a>
				<a href="#" class="widget-control widget-control-full-screen widget-control-show-when-full" data-toggle="tooltip" data-placement="left" title="" data-original-title="Exit Full Screen"><i class="fa fa-expand"></i></a>
				<a href="#" class="widget-control widget-control-refresh" data-toggle="tooltip" data-placement="top" title="" data-original-title="Refresh"><i class="fa fa-refresh"></i></a>
				<a href="#" class="widget-control widget-control-minimize" data-toggle="tooltip" data-placement="top" title="" data-original-title="Minimize"><i class="fa fa-minus-circle"></i></a>
			</div>
            <h3><i class="fa fa-ok-circle"></i>create new data penjualan</h3>
        </div>
			<div class="widget-content">
				<div class="row">
					<div class="col-md-12">
						
						<?php $form = ActiveForm::begin([
							'id' => 'create-role-form',
							'options' => ['class' => 'form-horizontal', 'data-toggle'=>'validator', 'role'=>'form'],
							'fieldConfig' => [
							'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
							'labelOptions' => ['class' => 'col-lg-1 control-label'],
							],
						]); ?>

								<div class="form-group">
									<label>No Nota</label>
									<?= Html::input("text", "no nota", null, ["placeholder"=>"No Nota", "required"=>"required", "class"=>"form-control"]) ?>
								</div>

								<div class="form-group">
									<label>Tanggal</label>
									<?= Html::input("text", "tanggal", null, ["placeholder"=>"Tanggal", "required"=>"required", "class"=>"form-control"]) ?>
								</div>

								<div class="form-group">
									<label>Nilai Penjualan</label>
									<?= Html::input("text", "nilai penjualan", null, ["placeholder"=>"Nilai Penjualan", "required"=>"required", "class"=>"form-control"]) ?>
								</div>

								<div class="form-group">
									<label>Uang Muka</label>
									<?= Html::input("text", "uang muka", null, ["placeholder"=>"Uang Muka", "required"=>"required", "class"=>"form-control"]) ?>
								</div>
								
								<div class="form-group">
									<label>PPN</label>
									<?= Html::input("text", "ppn", null, ["placeholder"=>"PPN", "required"=>"required", "class"=>"form-control"]) ?>
								</div>
								
								<div class="form-group">
									<label>Beban Angkut</label>
									<?= Html::input("text", "beban angkut", null, ["placeholder"=>"Beban Angkut", "required"=>"required", "class"=>"form-control"]) ?>
								</div>
								
								<div class="form-group">
									<label>Total</label>
									<?= Html::input("text", "total", null, ["placeholder"=>"Total", "required"=>"required", "class"=>"form-control"]) ?>
								</div>
								
								<div class="form-group">
									<label>Uang Muka</label>
									<?= Html::input("text", "contact person", null, ["placeholder"=>"Contact Person", "required"=>"required", "class"=>"form-control"]) ?>
								</div>


								<?= Html::submitButton('Save', ['class' => 'btn btn-primary']) ?>

						<?php ActiveForm::end(); ?>

					</div>
				</div>
			</div>
	</div>
</div>	


<!-- 
<h3>Create new user type</h3>
<?php $form = ActiveForm::begin([
	'id' => 'create-user-type-form',
	'options' => ['class' => 'form-horizontal', 'data-toggle'=>'validator'],
	'fieldConfig' => [
	'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
	'labelOptions' => ['class' => 'col-lg-1 control-label'],
	],
]); ?>

	<div class="form-group">
		<div class="col-lg-offset-1 col-lg-11">
			<?= Html::input("text", "id", null, ["placeholder"=>"ID", "required"=>"required"]) ?>
		</div>
	</div>

	<div class="form-group">
		<div class="col-lg-offset-1 col-lg-11">
			<?= Html::input("text", "username", null, ["placeholder"=>"Username", "required"=>"required"]) ?>
		</div>
	</div>

	<div class="form-group">
		<div class="col-lg-offset-1 col-lg-11">
			<?= Html::input("text", "alamat", null, ["placeholder"=>"Alamat", "required"=>"required"]) ?>
		</div>
	</div>

	<div class="form-group">
		<div class="col-lg-offset-1 col-lg-11">
			<?= Html::input("text", "sec_question", "nama project?", ["required"=>"required"]) ?>
		</div>
	</div>

	<div class="form-group">
		<div class="col-lg-offset-1 col-lg-11">
			<?= Html::input("text", "sec_answer", "autocom", ["required"=>"required"]) ?>
		</div>
	</div>

	<label>User type will be attached</label>

	<div class="form-group">
		<div class="col-lg-offset-1 col-lg-11">
			<ul>
			<?php
				foreach (UserType::find()->asArray()->all() as $key => $value) {
					echo "<li>";
						echo Html::radio("user_type", false, ["label"=>$value["name"], "value"=>$value["id"]]);
					echo "</li>";
				}
			?>
			</ul>
		</div>
	</div>

	<div class="form-group">
		<div class="col-lg-offset-1 col-lg-11">
			<?= Html::submitButton('Save', ['class' => 'btn btn-primary']) ?>
		</div>
	</div>

<?php ActiveForm::end(); ?>
 -->

autocom/views/warehouse/index.php
<h1>WAREHOUSE</h1>

autocom/views/warehouse/user_list.php
<?php
use yii\helpers\Html;

use app\models\WUsers;

$model = new WUsers();
?>



<div class="col-md-12">
    <div class="widget widget-green">
        <div class="widget-title">
            <div class="widget-controls">
				<a href="#" class="widget-control widget-control-full-screen" data-toggle="tooltip" data-placement="top" title="" data-original-title="Full Screen"><i class="fa fa-expand"></i></a>
				<a href="#" class="widget-control widget-control-full-screen widget-control-show-when-full" data-toggle="tooltip" data-placement="left" title="" data-original-title="Exit Full Screen"><i class="fa fa-expand"></i></a>
				<a href="#" class="widget-control widget-control-refresh" data-toggle="tooltip" data-placement="top" title="" data-original-title="Refresh"><i class="fa fa-refresh"></i></a>
				<a href="#" class="widget-control widget-control-minimize" data-toggle="tooltip" data-placement="top" title="" data-original-title="Minimize"><i class="fa fa-minus-circle"></i></a>
			</div>
            <h3><i class="fa fa-ok-circle"></i>list of user</h3>
        </div>
			<div class="widget-content">
				<div class="row">
					<div class="col-md-12">
						<a data-toggle="tooltip" data-placement="top" data-original-title="Tambah user warehouse" href="<?= Yii::$app->urlManager->createUrl(['warehouse/create-user']) ?>" class="btn btn-success btn-sm"><i class="glyphicon glyphicon-plus"></i></a>
						<span> </span>
						<a data-toggle="tooltip" data-placement="top" data-original-title="Matikan semua akses" href="<?= Yii::$app->urlManager->createUrl(['warehouse/create-user']) ?>" class="btn btn-primary btn-sm"><i class="fa fa-unlock"></i></a>
						<table class="table">
							<thead>
								<tr>
									<th>No</th>
									<th>Username</th>
									<th>Nama</th>
									<th>Email</th>
									<th>User type</th>
									<th width="150px">Action</th>
								</tr>
							</thead>
							<tbody>
								<?php $i=1; foreach ( $model->findUser() as $key => $value) { 
									if ($value['user_type_name'] == 'admin warehouse'
										||$value['user_type_name'] == 'kepala gudang warehouse'
										||$value['user_type_name'] == 'supervisor warehouse'
										||$value['user_type_name'] == 'operator warehouse'
									) {

									?>
									<tr>
										<td><?=$i?></td>
										<td><?=$value['username']?></td>
										<td><?=$value['nama_user']?></td>
										<td><?=$value['email']?></td>
										<td><?=$value['user_type_name']?></td>
										<td>
											<?php if ($value['unlocked']==1) { ?>
											 	<a href="" class="btn btn-danger btn-sm"  data-toggle="tooltip" data-placement="top" data-original-title="Stop hak akses"> <i class="glyphicon fa fa-lock"></i></a>
											 <?php }else{ ?>
												 <a href="" class="btn btn-primary btn-sm"  data-toggle="tooltip" data-placement="top" data-original-title="Buka hak akses"> <i class="glyphicon fa fa-unlock"></i></a>
											 <?php } ?>
											<a href="<?= Yii::$app->urlManager->createUrl(['warehouse/update-user',"id"=>$value['id']])?>" class="btn btn-primary btn-sm"><i class="glyphicon glyphicon-pencil"></i></a>
											<a href="<?= Yii::$app->urlManager->createUrl(['warehouse/delete-user',"id"=>$value['id']])?>" class="btn btn-danger btn-sm"><i class="glyphicon glyphicon-trash"></i></a>
										</td>
									</tr>
								<?php $i++; } } ?>
							</tbody>
						</table>
					</div>
				</div>
			</div>
	</div>
</div>	



<!-- 
<?= Html::a("Create new user", Yii::$app->urlManager->createUrl(['warehouse/create-user']), ["class"=>["btn","btn-primary"]])?>
<table border = "1" style="border-collapse:collapse">
	<tr>
		<th>No</th>
		<th>Username</th>
		<th>Email</th>
		<th>User type</th>
		<th>Action</th>
	</tr>
<?php $i=1; foreach ( $model->findUser() as $key => $value) { ?>
	<tr>
		<td><?=$i?></td>
		<td><?=$value['username']?></td>
		<td><?=$value['email']?></td>
		<td><?=$value['user_type_name']?></td>
		<td>
			<?= Html::a("edit", Yii::$app->urlManager->createUrl(['warehouse/update-user',"id"=>$value['id']]), [])?> | 
			<?= Html::a("delete", Yii::$app->urlManager->createUrl(['warehouse/delete-user',"id"=>$value['id']]),[])?>
		</td>
	</tr>
<?php $i++; } ?>
</table>
 -->