autocom/controllers/SecurityController.php
<?php

namespace app\controllers;

use Yii;
use app\controllers\SecureController;

use app\models\Role;
use app\models\RoleModule;
use app\models\UserType;
use app\models\User;

class SecurityController extends SecureController{
	public $layout = "security_layout";

	public function actionIndex(){
		return $this->render('index');
	}

	public function actionRoleManagement(){
		if($this->isSelectAllowed()){
			return $this->render('role_list');	
		}else{
			echo "You don't have access here";die;
		}
		
	}

	public function actionDetailRole(){
		if($this->isSelectAllowed()){
			return $this->render('detail_role');	
		}else{
			echo "You don't have access here";die;
		}
	}

	public function actionCreateRole(){
		if($this->isInsertAllowed()){
			if(Yii::$app->request->post()){
				$roleModel = new Role();
				$roleModel->saveRole(Yii::$app->request->post());
				/*return $this->render('role_list');*/
				return $this->redirect(['security/role-management']);
			}

        	return $this->render('create_role');
        }else{
        	echo "You don't have access here";die;	
        }
	}

	public function actionUpdateRole(){
		if($this->isUpdateAllowed()){
			if(Yii::$app->request->post()){
				$role = Role::findOne(Yii::$app->request->get()['id']);
				$role->name = Yii::$app->request->post()['role'];
				$role->update();

				$rowsDeleted = RoleModule::deleteAll('role = '.Yii::$app->request->get()['id']);

				$roleModel = new Role();
				$roleModel->updateRole(Yii::$app->request->get()['id'], Yii::$app->request->post());

				/*return $this->render('role_list');*/
				return $this->redirect(['security/role-management']);
			}

        	return $this->render('update_role');
        }else{
        	echo "You don't have access here";die;	
        }
	}

	public function actionDeleteRole(){
		if($this->isDeleteAllowed()){
			if(Yii::$app->request->get()){
				RoleModule::deleteAll('role = '.Yii::$app->request->get()['id']);
				Role::deleteAll('id = '.Yii::$app->request->get()['id']);

				/*return $this->render('role_list');*/
				return $this->redirect(['security/role-management']);
			}

        	return $this->render('role_list');
        }else{
        	echo "You don't have access here";die;	
        }
	}

	/**
	* start for handling user type management
	*/

	public function actionUserTypeManagement(){
		if($this->isSelectAllowed()){
			return $this->render('user_type_list');	
		}else{
			echo "You don't have access here";die;
		}
		
	}

	public function actionCreateUserType(){
		if($this->isInsertAllowed()){
			if(Yii::$app->request->post()){
				$userTypeModel = new UserType();
				$userTypeModel->name = Yii::$app->request->post()['name'];
				$userTypeModel->role = Yii::$app->request->post()['role'];
				$userTypeModel->save();

				/*return $this->render('user_type_list');*/
				return $this->redirect(['security/user-type-management']);
			}

        	return $this->render('create_user_type');
        }else{
        	echo "You don't have access here";die;	
        }
	}

	public function actionUpdateUserType(){
		if($this->isUpdateAllowed()){
			if(Yii::$app->request->post()){
				$userTypeModel = UserType::findOne(Yii::$app->request->get()['id']);
				$userTypeModel->name = Yii::$app->request->post()['name'];
				$userTypeModel->role = Yii::$app->request->post()['role'];
				$userTypeModel->update();

				/*return $this->render('user_type_list');*/
				return $this->redirect(['security/user-type-management']);
			}

        	return $this->render('update_user_type');
        }else{
        	echo "You don't have access here";die;	
        }
	}

	public function actionDeleteUserType(){
		if($this->isDeleteAllowed()){
			if(Yii::$app->request->get()){
				UserType::deleteAll('id = '.Yii::$app->request->get()['id']);

				/*return $this->render('user_type_list');*/
				return $this->redirect(['security/user-type-management']);
			}

        	return $this->render('user_type_list');
        }else{
        	echo "You don't have access here";die;	
        }
	}

	public function actionUserManagement(){
		if($this->isSelectAllowed()){
			return $this->render('user_list');	
		}else{
        	echo "You don't have access here";die;	
        }
	}

	public function actionCreateUser(){
		if($this->isInsertAllowed()){
			if(Yii::$app->request->post()){

				$new_user = new User();
				$new_user->saveBySQL(Yii::$app->request->post());

				return $this->redirect(['security/user-management']);
			}

        	return $this->render('create_user');
        }else{
        	echo "You don't have access here";die;	
        }
	}

	public function actionUpdateUser(){
		if($this->isUpdateAllowed()){
			if(Yii::$app->request->post()){
				$user = User::findOne(Yii::$app->request->get()['id']);
				$user->username = Yii::$app->request->post()['username'];
		        $user->email = Yii::$app->request->post()['email'];
		        $user->sec_question = Yii::$app->request->post()['sec_question'];
		        $user->sec_answer = Yii::$app->request->post()['sec_answer'];
		        $user->user_type = Yii::$app->request->post()['user_type'];
		        $user->authKey = "";
		        $user->accessToken = "";
		        $user->update();

				/*return $this->render('user_list');*/
				return $this->redirect(['security/user-management']);
			}

        	return $this->render('update_user');
        }else{
        	echo "You don't have access here";die;	
        }
	}

	public function actionDeleteUser(){
		if($this->isDeleteAllowed()){
			if(Yii::$app->request->get()){
				User::deleteAll('id = '.Yii::$app->request->get()['id']);

				/*return $this->render('user_list');*/
				return $this->redirect(['security/user-management']);
			}

        	return $this->render('user_list');
        }else{
        	echo "You don't have access here";die;	
        }
	}
}

?>

autocom/views/security/create_role.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

use app\models\Module;
use app\models\HakAkses;
?>
<div class="col-md-12">
    <div class="widget widget-green">
        <div class="widget-title">
            <div class="widget-controls">
				<a href="#" class="widget-control widget-control-full-screen" data-toggle="tooltip" data-placement="top" title="" data-original-title="Full Screen"><i class="fa fa-expand"></i></a>
				<a href="#" class="widget-control widget-control-full-screen widget-control-show-when-full" data-toggle="tooltip" data-placement="left" title="" data-original-title="Exit Full Screen"><i class="fa fa-expand"></i></a>
				<a href="#" class="widget-control widget-control-refresh" data-toggle="tooltip" data-placement="top" title="" data-original-title="Refresh"><i class="fa fa-refresh"></i></a>
				<a href="#" class="widget-control widget-control-minimize" data-toggle="tooltip" data-placement="top" title="" data-original-title="Minimize"><i class="fa fa-minus-circle"></i></a>
			</div>
            <h3><i class="fa fa-ok-circle"></i>create new role</h3>
        </div>
			<div class="widget-content">
				<div class="row">
					<div class="col-md-12">
						
						<?php $form = ActiveForm::begin([
							'id' => 'create-role-form',
							'options' => ['class' => 'form-horizontal', 'data-toggle'=>'validator', 'role'=>'form'],
							'fieldConfig' => [
							'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
							'labelOptions' => ['class' => 'col-lg-1 control-label'],
							],
						]); ?>
							<div class="form-group">
				                <label>Role name</label>
				                <input type="text" class="form-control" placeholder="" name="role" required = "required">
				           	</div>
							<!-- <?= Html::input("text", "role", null, ["placeholder"=>"role name", "required"=>"required"]) ?> -->
							<div class="form-group">
                				<label>Module and it's access rule</label><br>
								<table>
								<?php
									$module = Module::find()->all();
									$hakAkses = HakAkses::find()->all();
									$i = 0;
									foreach ($module as $key => $value) {
										echo "<tr>";
											echo "<td>";
												echo Html::checkbox("module[$i][name]", false, ["label"=>$value["name"], "value"=>$value["id"]]);
											echo "</td>";
											echo "<td>";
											foreach ($hakAkses as $key2 => $value2) {
												echo Html::checkbox("module[$i][role][]", false, ["label"=>$value2["name"], "value"=>$value2["id"]]);
											}
											echo "</td>";
										echo "</tr>";
										$i++;
									}
								?>
								</table>
							</div>

							<?= Html::submitButton('Save', ['class' => 'btn btn-primary', 'name' => 'save-button']) ?>

						<?php ActiveForm::end(); ?>

					</div>
				</div>
			</div>
	</div>
</div>	

autocom/views/security/create_user.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

use app\models\UserType;
?>



<div class="col-md-12">
    <div class="widget widget-green">
        <div class="widget-title">
            <div class="widget-controls">
				<a href="#" class="widget-control widget-control-full-screen" data-toggle="tooltip" data-placement="top" title="" data-original-title="Full Screen"><i class="fa fa-expand"></i></a>
				<a href="#" class="widget-control widget-control-full-screen widget-control-show-when-full" data-toggle="tooltip" data-placement="left" title="" data-original-title="Exit Full Screen"><i class="fa fa-expand"></i></a>
				<a href="#" class="widget-control widget-control-refresh" data-toggle="tooltip" data-placement="top" title="" data-original-title="Refresh"><i class="fa fa-refresh"></i></a>
				<a href="#" class="widget-control widget-control-minimize" data-toggle="tooltip" data-placement="top" title="" data-original-title="Minimize"><i class="fa fa-minus-circle"></i></a>
			</div>
            <h3><i class="fa fa-ok-circle"></i>create new user</h3>
        </div>
			<div class="widget-content">
				<div class="row">
					<div class="col-md-12">
						
						<?php $form = ActiveForm::begin([
							'id' => 'create-role-form',
							'options' => ['class' => 'form-horizontal', 'data-toggle'=>'validator', 'role'=>'form'],
							'fieldConfig' => [
							'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
							'labelOptions' => ['class' => 'col-lg-1 control-label'],
							],
						]); ?>

								<div class="form-group">
									<label>Username</label>
									<?= Html::input("text", "username", null, ["placeholder"=>"Username", "required"=>"required", "class"=>"form-control"]) ?>
								</div>

								<div class="form-group">
									<label>Password</label>
									<?= Html::input("password", "password", null, ["placeholder"=>"Password", "required"=>"required", "class"=>"form-control"]) ?>
								</div>

								<div class="form-group">
									<label>Email</label>
									<?= Html::input("email", "email", null, ["placeholder"=>"Email", "required"=>"required", "class"=>"form-control"]) ?>
								</div>

								<div class="form-group">
									<label>Secuence Question</label>
									<?= Html::input("text", "sec_question", "nama project?", ["required"=>"required", "class"=>"form-control"]) ?>
								</div>

								<div class="form-group">
									<label>Secuence Answer</label>
									<?= Html::input("text", "sec_answer", "autocom", ["required"=>"required", "class"=>"form-control"]) ?>
								</div>

								<div class="form-group">
									<label>User type will be attached</label>
									<?php
										foreach (UserType::find()->asArray()->all() as $key => $value) {
									?>
									<div class="radio">
					                  	<label>
					                  		<?php
					                  			echo Html::radio("user_type", false, ["label"=>$value["name"], "value"=>$value["id"]]);
					                  		?>
					                  	</label>
					                </div>
									<?php
										}
									?>
								</div>

								<?= Html::submitButton('Save', ['class' => 'btn btn-primary']) ?>

						<?php ActiveForm::end(); ?>

					</div>
				</div>
			</div>
	</div>
</div>	


<!-- 
<h3>Create new user type</h3>
<?php $form = ActiveForm::begin([
	'id' => 'create-user-type-form',
	'options' => ['class' => 'form-horizontal', 'data-toggle'=>'validator'],
	'fieldConfig' => [
	'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
	'labelOptions' => ['class' => 'col-lg-1 control-label'],
	],
]); ?>

	<div class="form-group">
		<div class="col-lg-offset-1 col-lg-11">
			<?= Html::input("text", "username", null, ["placeholder"=>"Username", "required"=>"required"]) ?>
		</div>
	</div>

	<div class="form-group">
		<div class="col-lg-offset-1 col-lg-11">
			<?= Html::input("password", "password", null, ["placeholder"=>"Password", "required"=>"required"]) ?>
		</div>
	</div>

	<div class="form-group">
		<div class="col-lg-offset-1 col-lg-11">
			<?= Html::input("email", "email", null, ["placeholder"=>"Email", "required"=>"required"]) ?>
		</div>
	</div>

	<div class="form-group">
		<div class="col-lg-offset-1 col-lg-11">
			<?= Html::input("text", "sec_question", "nama project?", ["required"=>"required"]) ?>
		</div>
	</div>

	<div class="form-group">
		<div class="col-lg-offset-1 col-lg-11">
			<?= Html::input("text", "sec_answer", "autocom", ["required"=>"required"]) ?>
		</div>
	</div>

	<label>User type will be attached</label>

	<div class="form-group">
		<div class="col-lg-offset-1 col-lg-11">
			<ul>
			<?php
				foreach (UserType::find()->asArray()->all() as $key => $value) {
					echo "<li>";
						echo Html::radio("user_type", false, ["label"=>$value["name"], "value"=>$value["id"]]);
					echo "</li>";
				}
			?>
			</ul>
		</div>
	</div>

	<div class="form-group">
		<div class="col-lg-offset-1 col-lg-11">
			<?= Html::submitButton('Save', ['class' => 'btn btn-primary']) ?>
		</div>
	</div>

<?php ActiveForm::end(); ?>
 -->

autocom/views/security/create_user_type.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

use app\models\Role;
?>



<div class="col-md-12">
    <div class="widget widget-green">
        <div class="widget-title">
            <div class="widget-controls">
				<a href="#" class="widget-control widget-control-full-screen" data-toggle="tooltip" data-placement="top" title="" data-original-title="Full Screen"><i class="fa fa-expand"></i></a>
				<a href="#" class="widget-control widget-control-full-screen widget-control-show-when-full" data-toggle="tooltip" data-placement="left" title="" data-original-title="Exit Full Screen"><i class="fa fa-expand"></i></a>
				<a href="#" class="widget-control widget-control-refresh" data-toggle="tooltip" data-placement="top" title="" data-original-title="Refresh"><i class="fa fa-refresh"></i></a>
				<a href="#" class="widget-control widget-control-minimize" data-toggle="tooltip" data-placement="top" title="" data-original-title="Minimize"><i class="fa fa-minus-circle"></i></a>
			</div>
            <h3><i class="fa fa-ok-circle"></i>create new user type</h3>
        </div>
			<div class="widget-content">
				<div class="row">
					<div class="col-md-12">
						
						<?php $form = ActiveForm::begin([
							'id' => 'create-role-form',
							'options' => ['class' => 'form-horizontal', 'data-toggle'=>'validator', 'role'=>'form'],
							'fieldConfig' => [
							'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
							'labelOptions' => ['class' => 'col-lg-1 control-label'],
							],
						]); ?>
							<div class="form-group">
				                <label>User type</label>
				                <input type="text" class="form-control" placeholder="" name="name" required = "required">
				           	</div>
							<!-- <?= Html::input("text", "role", null, ["placeholder"=>"role name", "required"=>"required"]) ?> -->
							<div class="form-group">
                				<label>Role will be attached</label><br>
								<?php
									foreach (Role::find()->asArray()->all() as $key => $value) {
								?>
								<div class="radio">
				                  	<label>
				                  		<?php
				                  			echo Html::radio("role", false, ["label"=>$value["name"], "value"=>$value["id"]]);
				                  		?>
				                  	</label>
				                </div>
								<?php
									}
								?>
							</div>

							<?= Html::submitButton('Save', ['class' => 'btn btn-primary', 'name' => 'save-button']) ?>

						<?php ActiveForm::end(); ?>

					</div>
				</div>
			</div>
	</div>
</div>	


<!-- 
<h3>Create new user type</h3>
<?php $form = ActiveForm::begin([
	'id' => 'create-user-type-form',
	'options' => ['class' => 'form-horizontal', 'data-toggle'=>'validator'],
	'fieldConfig' => [
	'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
	'labelOptions' => ['class' => 'col-lg-1 control-label'],
	],
]); ?>

	<div class="form-group">
		<div class="col-lg-offset-1 col-lg-11">
			<?= Html::input("text", "name", null, ["placeholder"=>"user type name", "required"=>"required"]) ?>
		</div>
	</div>

	<label>Role will be attached</label>

	<div class="form-group">
		<div class="col-lg-offset-1 col-lg-11">
			<ul>
			<?php
				foreach (Role::find()->asArray()->all() as $key => $value) {
					echo "<li>";
						echo Html::radio("role", false, ["label"=>$value["name"], "value"=>$value["id"]]);
					echo "</li>";
				}
			?>
			</ul>
		</div>
	</div>

	<div class="form-group">
		<div class="col-lg-offset-1 col-lg-11">
			<?= Html::submitButton('Save', ['class' => 'btn btn-primary', 'name' => 'save-button']) ?>
		</div>
	</div>

<?php ActiveForm::end(); ?>
 -->

autocom/views/security/index.php
Welcome to security module:)

autocom/views/security/role_list.php
<?php
use yii\helpers\Html;

use app\models\Role;

$roleModel = new Role();
?>

<div class="col-md-12">
    <div class="widget widget-green">
        <div class="widget-title">
            <div class="widget-controls">
				<a href="#" class="widget-control widget-control-full-screen" data-toggle="tooltip" data-placement="top" title="" data-original-title="Full Screen"><i class="fa fa-expand"></i></a>
				<a href="#" class="widget-control widget-control-full-screen widget-control-show-when-full" data-toggle="tooltip" data-placement="left" title="" data-original-title="Exit Full Screen"><i class="fa fa-expand"></i></a>
				<a href="#" class="widget-control widget-control-refresh" data-toggle="tooltip" data-placement="top" title="" data-original-title="Refresh"><i class="fa fa-refresh"></i></a>
				<a href="#" class="widget-control widget-control-minimize" data-toggle="tooltip" data-placement="top" title="" data-original-title="Minimize"><i class="fa fa-minus-circle"></i></a>
			</div>
            <h3><i class="fa fa-ok-circle"></i>list of role</h3>
        </div>
			<div class="widget-content">
				<div class="row">
					<div class="col-md-12">
						<a href="<?= Yii::$app->urlManager->createUrl(['security/create-role'])?>" class="btn btn-success btn-sm"><i class="glyphicon glyphicon-plus"></i></a>
						<table class="table">
							<thead>
								<tr>
									<th>No</th>
									<th>Role Name</th>
									<th>Module Allowed</th>
									<th width="150px">Action</th>
								</tr>
							</thead>
							<tbody>
								<?php $i=1; foreach ( $roleModel->findRoleWithModule() as $key => $value) { ?>
									<tr>
										<td><?=$i?></td>
										<td><?=$value['role']?></td>
										<td><?=$value['module']?></td>
										<td>
											<a href="<?= Yii::$app->urlManager->createUrl(['security/detail-role',"id"=>$value['id_role']])?>" class="btn btn-success btn-sm"><i class="glyphicon glyphicon-search"></i></a>
											
											<a href="<?= Yii::$app->urlManager->createUrl(['security/update-role',"id"=>$value['id_role']])?>" class="btn btn-primary btn-sm"><i class="glyphicon glyphicon-pencil"></i></a>
											
											<a href="<?= Yii::$app->urlManager->createUrl(['security/delete-role',"id"=>$value['id_role']])?>" class="btn btn-danger btn-sm"><i class="glyphicon glyphicon-trash"></i></a>
										</td>
									</tr>
								<?php $i++; } ?>
							</tbody>
						</table>
					</div>
				</div>
			</div>
	</div>
</div>	

<!-- 
<?= Html::a("Create role", Yii::$app->urlManager->createUrl(['security/create-role']), ["class"=>["btn","btn-primary"]])?>
<table border = "1" style="border-collapse:collapse">
	<tr>
		<th>No</th>
		<th>Role Name</th>
		<th>Module Allowed</th>
		<th>Action</th>
	</tr>
<?php $i=1; foreach ( $roleModel->findRoleWithModule() as $key => $value) { ?>
	<tr>
		<td><?=$i?></td>
		<td><?=$value['role']?></td>
		<td><?=$value['module']?></td>
		<td>
			<?= Html::a("detail",Yii::$app->urlManager->createUrl(['security/detail-role',"id"=>$value['id_role']]), [])?> | 
			<?= Html::a("edit", Yii::$app->urlManager->createUrl(['security/update-role',"id"=>$value['id_role']]), [])?> | 
			<?= Html::a("delete", Yii::$app->urlManager->createUrl(['security/delete-role',"id"=>$value['id_role']]),[])?>
		</td>
	</tr>
<?php $i++; } ?>
</table> -->

autocom/views/security/user_list.php
<?php
use yii\helpers\Html;

use app\models\User;

$model = new User();
?>



<div class="col-md-12">
    <div class="widget widget-green">
        <div class="widget-title">
            <div class="widget-controls">
				<a href="#" class="widget-control widget-control-full-screen" data-toggle="tooltip" data-placement="top" title="" data-original-title="Full Screen"><i class="fa fa-expand"></i></a>
				<a href="#" class="widget-control widget-control-full-screen widget-control-show-when-full" data-toggle="tooltip" data-placement="left" title="" data-original-title="Exit Full Screen"><i class="fa fa-expand"></i></a>
				<a href="#" class="widget-control widget-control-refresh" data-toggle="tooltip" data-placement="top" title="" data-original-title="Refresh"><i class="fa fa-refresh"></i></a>
				<a href="#" class="widget-control widget-control-minimize" data-toggle="tooltip" data-placement="top" title="" data-original-title="Minimize"><i class="fa fa-minus-circle"></i></a>
			</div>
            <h3><i class="fa fa-ok-circle"></i>list of user</h3>
        </div>
			<div class="widget-content">
				<div class="row">
					<div class="col-md-12">
						<a href="<?= Yii::$app->urlManager->createUrl(['security/create-user']) ?>" class="btn btn-success btn-sm"><i class="glyphicon glyphicon-plus"></i></a>
						<table class="table">
							<thead>
								<tr>
									<th>No</th>
									<th>Username</th>
									<th>Email</th>
									<th>User type</th>
									<th width="150px">Action</th>
								</tr>
							</thead>
							<tbody>
								<?php $i=1; foreach ( $model->findUser() as $key => $value) { ?>
									<tr>
										<td><?=$i?></td>
										<td><?=$value['username']?></td>
										<td><?=$value['email']?></td>
										<td><?=$value['user_type_name']?></td>
										<td>
											
											<a href="<?= Yii::$app->urlManager->createUrl(['security/update-user',"id"=>$value['id']])?>" class="btn btn-primary btn-sm"><i class="glyphicon glyphicon-pencil"></i></a>
											
											<a href="<?= Yii::$app->urlManager->createUrl(['security/delete-user',"id"=>$value['id']])?>" class="btn btn-danger btn-sm"><i class="glyphicon glyphicon-trash"></i></a>
										</td>
									</tr>
								<?php $i++; } ?>
							</tbody>
						</table>
					</div>
				</div>
			</div>
	</div>
</div>	



<!-- 
<?= Html::a("Create new user", Yii::$app->urlManager->createUrl(['security/create-user']), ["class"=>["btn","btn-primary"]])?>
<table border = "1" style="border-collapse:collapse">
	<tr>
		<th>No</th>
		<th>Username</th>
		<th>Email</th>
		<th>User type</th>
		<th>Action</th>
	</tr>
<?php $i=1; foreach ( $model->findUser() as $key => $value) { ?>
	<tr>
		<td><?=$i?></td>
		<td><?=$value['username']?></td>
		<td><?=$value['email']?></td>
		<td><?=$value['user_type_name']?></td>
		<td>
			<?= Html::a("edit", Yii::$app->urlManager->createUrl(['security/update-user',"id"=>$value['id']]), [])?> | 
			<?= Html::a("delete", Yii::$app->urlManager->createUrl(['security/delete-user',"id"=>$value['id']]),[])?>
		</td>
	</tr>
<?php $i++; } ?>
</table>
 -->

autocom/views/security/user_type_list.php
<?php
use yii\helpers\Html;
use app\models\UserType;
?>

<div class="col-md-12">
    <div class="widget widget-green">
        <div class="widget-title">
            <div class="widget-controls">
				<a href="#" class="widget-control widget-control-full-screen" data-toggle="tooltip" data-placement="top" title="" data-original-title="Full Screen"><i class="fa fa-expand"></i></a>
				<a href="#" class="widget-control widget-control-full-screen widget-control-show-when-full" data-toggle="tooltip" data-placement="left" title="" data-original-title="Exit Full Screen"><i class="fa fa-expand"></i></a>
				<a href="#" class="widget-control widget-control-refresh" data-toggle="tooltip" data-placement="top" title="" data-original-title="Refresh"><i class="fa fa-refresh"></i></a>
				<a href="#" class="widget-control widget-control-minimize" data-toggle="tooltip" data-placement="top" title="" data-original-title="Minimize"><i class="fa fa-minus-circle"></i></a>
			</div>
            <h3><i class="fa fa-ok-circle"></i>list of user type</h3>
        </div>
			<div class="widget-content">
				<div class="row">
					<div class="col-md-12">
						<a href="<?= Yii::$app->urlManager->createUrl(['security/create-user-type']) ?>" class="btn btn-success btn-sm"><i class="glyphicon glyphicon-plus"></i></a>
						<table class="table">
							<thead>
								<tr>
									<th>No</th>
									<th>User Type Name</th>
									<th>Role Name</th>
									<th width="150px">Action</th>
								</tr>
							</thead>
							<tbody>
								<?php $i=1; foreach ( UserType::find()->with('role0')->asArray()->all() as $key => $value) { ?>
									<tr>
										<td><?=$i?></td>
										<td><?=$value['name']?></td>
										<td><?=$value['role0']['name']?></td>
										<td>
											
											<a href="<?= Yii::$app->urlManager->createUrl(['security/update-user-type',"id"=>$value['id']])?>" class="btn btn-primary btn-sm"><i class="glyphicon glyphicon-pencil"></i></a>
											
											<a href="<?= Yii::$app->urlManager->createUrl(['security/delete-user-type',"id"=>$value['id']])?>" class="btn btn-danger btn-sm"><i class="glyphicon glyphicon-trash"></i></a>
										</td>
									</tr>
								<?php $i++; } ?>
							</tbody>
						</table>
					</div>
				</div>
			</div>
	</div>
</div>	




<!-- 
<?php
?>
<?= Html::a("Create user type", Yii::$app->urlManager->createUrl(['security/create-user-type']), ["class"=>["btn","btn-primary"]])?>
<table border = "1" style="border-collapse:collapse">
	<tr>
		<th>No</th>
		<th>User Type Name</th>
		<th>Role Name</th>
		<th>Action</th>
	</tr>
<?php $i=1; foreach ( UserType::find()->with('role0')->asArray()->all() as $key => $value) { ?>
	<tr>
		<td><?=$i?></td>
		<td><?=$value['name']?></td>
		<td><?=$value['role0']['name']?></td>
		<td>
			<?= Html::a("edit", Yii::$app->urlManager->createUrl(['security/update-user-type',"id"=>$value['id']]), [])?> | 
			<?= Html::a("delete", Yii::$app->urlManager->createUrl(['security/delete-user-type',"id"=>$value['id']]),[])?>
		</td>
	</tr>
<?php $i++; } ?>
</table> -->